### ISSUE TITLE
Single-machine cloud sites cannot be created anymore

### ISSUE THREAD

**Issue by robertodauria** [m-lab/siteinfo#188]
It is possible to create a cloud node running ndt via [a script in the k8s-support repository](https://github.com/m-lab/k8s-support/blob/master/manage-cluster/add_ndt_virtual_node.sh). However, NDT pods on these cloud nodes will fail to start if a corresponding entry in siteinfo does not exist:

```
uuid-annotator/siteannotator/server.go:42: Could not load annotation db (error: Hostname Not Found)
```

It looks like creating single-machine sites isn't supported by siteinfo anymore. E.g.

```
sitesDefault {
  name: 'fra0t',
  annotations+: {
    type: 'cloud',
  },
  machines+: {
    mlab1+: {
      model: 'r630',
      project: 'mlab-sandbox',
    },
  },
  network+: {
    ipv4+: {
      prefix: '34.107.116.1',
    },

[...]
```
Outputs the following error during the GCB build:

```
Step #4: time java -Xmx2G -cp /usr/bin/sjsonnet.jar sjsonnet.SjsonnetMain -J . --ext-str version=v1 --ext-code retired=false formats/v1/sites/sites.json.jsonnet > output/v1/sites/sites.json
Step #4: sjsonnet.Error: Machine indexes for single-machine sites must be 1
Step #4:     at .(lib/site.jsonnet:69:13)
```

@nkinkade I know we had cloud nodes at some point in the past. Do you know if there's a way to add them to siteinfo (and I'm doing something wrong above), or it's just not supported anymore?

**Comment by nkinkade** [comment]
@robertodauria: Ah... I think this is the change that is causing this for you:

https://github.com/m-lab/siteinfo/pull/119/files#diff-c05436c5cf2682ef525bf7aa09f6c6d948f82b53c02fac6103d26f96fd32213bR11

Are you able to to completely override `machines` rather than using `machines+: {`. For example, does this work?:

```
  },
  machines: {
    mlab1: {
      disk: 'sda',
      iface: 'eth0',
      model: 'r630',
      project: 'mlab-sandbox',
    },
  },
  network+: {
```

**Comment by nkinkade** [comment]
@robertodauria: I see you [made a new commit](https://github.com/m-lab/siteinfo/commit/2f430658e1b3e039ddeae909d3a3d17e255d78a0), but I suspect you also need to remove the `+`  from `mlab1+`, and you will also need to explicitly set  all machine fields, since we are not inheriting any of the defaults. Literally this, I think:

```
  machines: {
    mlab1: {
      disk: 'sda',
      iface: 'eth0',
      model: 'gce',
      project: 'mlab-sandbox',
    },
  },

**Comment by robertodauria** [comment]
> @robertodauria: I see you [made a new commit](https://github.com/m-lab/siteinfo/commit/2f430658e1b3e039ddeae909d3a3d17e255d78a0), but I suspect you also need to remove the `+`  from `mlab1+`, and you will also need to explicitly set  all machine fields, since we are not inheriting any of the defaults. Literally this, I think:
> 
> ```
>   machines: {
>     mlab1: {
>       disk: 'sda',
>       iface: 'eth0',
>       model: 'gce',
>       project: 'mlab-sandbox',
>     },
>   },

That worked. Thanks!
