### ISSUE TITLE
Siteinfo deployments should create various site-related configurations

### ISSUE THREAD

**Issue by nkinkade** [m-lab/siteinfo#83]
siteinfo is now the definitive location for adding and removing sites, and houses all manner of data about each site. It makes sense for siteinfo deployments to start creating various private site information/configurations that are not stored in the siteinfo repository, including, but not necessarily limited to:

* Adding ePoxy GCD entities
* Adding BMC GCD entities
* Adding snmp-community GCD entities
* Deploying updated snmp-exporter configs to prometheus-federation cluster
* DNS deployments for siteinfo changes

@robertodauria : am I missing anything?

**Comment by nkinkade** [comment]
@robertodauria: I've been thinking about this a bit more this afternoon, and, while logical, I'm starting to think this repository is not the [easy] place for these configs to be deployed from. The issue I'm finding is that by the time the Google Cloud Build is deploying in this repository it is no longer easy to determine which sites were added or removed.

Currently, we deploy switch SNMP communities to GCD when a switch config is generated using `genconfig.py` in the switch-config repository. It occurs to me that it would be quite easy, though not very logical, to have that same script also create ePoxy and BMC GCD entities. 

What do you think?

**Comment by robertodauria** [comment]
@nkinkade My original idea on how to go about this was to compare the list of sites in the `sites/` folder of this repo with what's currently on GCD at build time, then create the missing ones. That way, we don't have to explicitly tell the build process which sites have been added or removed. If we also want to automate removals in future, this approach makes it pretty easy to do and keeps entities always in sync with what's on siteinfo.

To make that possible, a few days ago I merged [this PR](https://github.com/m-lab/bmctool/pull/34) which allows bmctool to list all the entities for a given `--project`. A similar feature would be needed for epoxy_admin, whose `list` command currently must be called with a single `--hostname` to work.

However, I see these two (BMC and ePoxy entities) differently than SNMP community strings, for which the switch-config feels like a more natural place to me.

Does the above help?

**Comment by nkinkade** [comment]
@robertodauria: I saw your changes to bmctool. I guess I was thinking that that solution seems rather hacky to me for some reason. Maybe it isn't? The idea of writing some shell script that lists a directory (excluding certain files) or tries to parse sites.jsonnet or downloads one of the JSON files to generate a list of valid sites, and then making calls to GCD to generate yet another list, and then trying to compare those lists.... it seems like bending over backward to figure out what is new. I would much rather find a way of doing this such that the script knew beforehand exactly which sites need to be added. This was my thinking is half-heartedly suggesting we could do it in in switch-config repo through genconfig.py, but I admit that the switch-config repo doesn't seem like a logical place either.

Thoughts?

**Comment by robertodauria** [comment]
I agree on the hackyness of comparing the two lists, but I wouldn't know how to make the script know beforehand which sites/entities need to be added, otherwise, since siteinfo and Datastore are the only sources of truth for that. If we drop the requirement that this needs to happen at deployment time, though, I have a proposal.

I think what we're trying to create is a generic tool to "Add a new M-Lab site", which involves several steps. Running `genconfig.py` is just one of them - namely, generating a JSON configuration for the switch - so it seems a bit innatural to let it create the BMC and ePoxy entities.

What if we add a script to siteinfo, to be run manually (`./add-site.sh xyzNN`) that:
1. creates the BMC/ePoxy entities
2. creates a new empty `xyzNN.jsonnet` file under `sites/` (to be filled manually)

This does not involve any additional work for the operator, compared with the current workflow of creating everything manually. It does not automate the process, as we still need to run the script, but it makes sure new sites are created with all the pieces in place.

The new workflow would look like this:
1. go to the siteinfo repository
2. run `./add-site.sh xyzNN`
3. go to the switch-config repository
4. run `genconfig.py [...]`

We could merge these steps together if we let `add-site.sh` clone the switch-config repo and run `genconfig.py`.

After writing the above, I'm not totally convinced of this solution either. :\

It simplifies things, but it feels like moving backwards towards an imperative approach after having worked hard to move to a declarative approach (which is one of the reasons behind this repository) and it leaves the door open for human error - for example, one could just create a new `.jsonnet` manually, without using the script, and forget about BMC/ePoxy entities.

I need to think about this more. Perhaps just letting `genconfig.py` create those entities while we figure out a better approach would be a good compromise?

**Comment by nkinkade** [comment]
@robertodauria: I somewhat like your script idea, but dislike someone having to remember to manually run it. What if we leveraged git hooks for this?  Possibly a `post-commit` hook that did something **very** roughly like the following

```
#!/bin/bash

SITES_CHANGES=$(git diff HEAD~1 HEAD -- sites.jsonnet | grep '^[+-]\s')
if [[ -n $SITES_CHANGES ]]; then
  for site_change in "$SITES_CHANGES"; do
    site=$(echo $site_change | awk '{print $2}' | cut -d: -f1)
    if [[ ${site_change:0:1} == '-' ]]; then
      echo "Removing GCD entries for ${site}."
      # Code to remove GCD entities below.
    else
      echo "Adding GCD entries for ${site}."
      # Code to add GCD entities below.
    fi  
  done
fi
```

This would check to see if `sites.jsonnet` was modified in the commit, and if it was, it parses the changes to try to determine which sites may have been added or removed. If a site was added, then the script would add the necessary GCD entities for ePoxy and the BMC, else if a site was removed then it would remove all those entities.

What do you think?

I suppose we could also try to do this  through Google Cloud Build, which does have access to the most recent commit that triggered the build, though that seems harder, since a push that triggered a build may have had many commits, the most recent of which may not have updated sites.jsonnet.

**Comment by robertodauria** [comment]
@nkinkade Is there any other place where we use git hooks, or this would be the only case? I think Cloud Build might be a better option in terms of visibility (we all have access to the build logs) and "least surprise", since we do everything else with Travis and/or Cloud Build.

**Comment by nkinkade** [comment]
This issue is now pending outcomes of this nascent document:

https://docs.google.com/document/d/1s2OqzBXnvsUvAklBwfLMLcVOJ8NYLi2xycI-uXm6enY/

**Comment by nkinkade** [comment]
This issues is advanced in one small part by PR m-lab/siteinfo/pull/100. There is still more work to be done for entities other than stage1 ISOs, however. I'm going to leave this issue open to track progress on the other entities (e.g., BMC GCD credentials, SNMP communities in GCD, and ePoxy GCD entities).

**Comment by nkinkade** [comment]
This has been done now for some time. Everything we want automated is now automated.
